version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo Downloading .env file from S3...
      - aws s3 cp s3://mtb-traveler/.env .env
      - echo Downloading aws-exports.js file from S3...
      - aws s3 cp s3://mtb-traveler/aws-exports.js src/aws-exports.js

  build:
    commands:
      - echo Build started on `date`
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: build
