version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo Downloading .env file from S3...
      - aws s3 cp s3://mtb-traveler/.env .env

  build:
    commands:
      - echo Build started on `date`
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
